# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 06:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yg_cms', '0002_auto_20160429_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=256, verbose_name='标题'),
        ),
    ]
